include: package:flutter_lints/flutter.yaml

analyzer:
  exclude: [ build/** ]
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true
  errors:
    avoid_unused_constructor_parameters: warning
    prefer_const_constructors: warning
    prefer_const_constructors_in_immutables: warning
    prefer_const_declarations: warning
    prefer_const_literals_to_create_immutables: warning
    omit_local_variable_types: ignore
    todo: ignore
    invalid_assignment: error
    missing_return: error
    unawaited_futures: error
    dead_code: warning
    empty_constructor_bodies: warning
    avoid_empty_else: warning
    avoid_shadowing_type_parameters: warning
    avoid_void_async: error
    empty_statements: warning
    prefer_final_locals: info
    curly_braces_in_flow_control_structures: warning
    unnecessary_await_in_return: warning
    unnecessary_lambdas: warning
    unnecessary_brace_in_string_interps: warning
    unnecessary_getters_setters: warning
    unnecessary_null_aware_assignments: warning
    unnecessary_const: warning
    unnecessary_new: warning
    unnecessary_null_in_if_null_operators: warning
    unnecessary_overrides: warning
    unnecessary_parenthesis: warning
    unnecessary_this: info
    avoid_relative_lib_imports: warning
    exhaustive_cases: warning
    always_declare_return_types: error
    prefer_single_quotes: error
    unsafe_html: error
    use_full_hex_values_for_flutter_colors: warning
linter:
  rules:
    avoid_unused_constructor_parameters: true
    prefer_const_constructors: true
    prefer_const_constructors_in_immutables: true
    prefer_const_declarations: true
    prefer_const_literals_to_create_immutables: true
    omit_local_variable_types: false
    unnecessary_await_in_return: false
    unnecessary_lambdas: true
    unnecessary_brace_in_string_interps: true
    unnecessary_getters_setters: true
    unnecessary_null_aware_assignments: true
    unnecessary_const: true
    unnecessary_new: true
    unnecessary_null_in_if_null_operators: true
    unnecessary_overrides: true
    unnecessary_parenthesis: true
    unnecessary_this: true
    prefer_final_locals: true
    prefer_final_fields: true
    avoid_void_async: true
    await_only_futures: true
    always_put_control_body_on_new_line: true
    #always_put_required_named_parameters_first: true
    annotate_overrides: true
    camel_case_types: true
    cancel_subscriptions: true
    close_sinks: true
    comment_references: true
    constant_identifier_names: true
    control_flow_in_finally: true
    empty_statements: true

    avoid_empty_else: true
    avoid_init_to_null: true
    avoid_relative_lib_imports: true
    avoid_return_types_on_setters: true
    avoid_shadowing_type_parameters: true
    avoid_types_as_parameter_names: true
    curly_braces_in_flow_control_structures: true
    empty_catches: true
    empty_constructor_bodies: true
    library_names: true
    library_prefixes: true
    no_duplicate_case_values: true
    null_closures: true
    prefer_contains: true
    prefer_is_empty: true
    prefer_is_not_empty: true
    prefer_iterable_whereType: true
    recursive_getters: true
    slash_for_doc_comments: true
    type_init_formals: true
    unawaited_futures: true
    unrelated_type_equality_checks: true
    use_rethrow_when_possible: true
    valid_regexps: true
    exhaustive_cases: true
    type_annotate_public_apis: true
    sort_child_properties_last: false
    always_use_package_imports: true
    always_declare_return_types: true
    prefer_single_quotes: true
    use_full_hex_values_for_flutter_colors: true

    library_private_types_in_public_api: false
    use_build_context_synchronously: false
    depend_on_referenced_packages: false
    no_leading_underscores_for_local_identifiers: false

    annotate_redeclares: true
    invalid_runtime_check_with_js_interop_types: true
    use_super_parameters: true
